services:
  # PostgreSQL Database
  db:
    image: postgres:latest
    container_name: postgres
    restart: no
    environment:
      POSTGRES_USER: ${IMDB_DEMO_DB_USER}
      POSTGRES_PASSWORD: ${IMDB_DEMO_DB_PASS}
      POSTGRES_DB: ${IMDB_DEMO_DB_NAME}
    ports:
      - ${IMDB_DEMO_DB_PORT}:${IMDB_DEMO_DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: