########################################################################################################################
# Environment Variables
imdb-demo.db.host=${IMDB_DEMO_DB_HOST}
imdb-demo.db.port=${IMDB_DEMO_DB_PORT}
imdb-demo.db.name=${IMDB_DEMO_DB_NAME}
imdb-demo.db.user=${IMDB_DEMO_DB_USER}
imdb-demo.db.pass=${IMDB_DEMO_DB_PASS}
########################################################################################################################
# Datasource Configuration
spring.datasource.url=jdbc:postgresql://${imdb-demo.db.host}:${imdb-demo.db.port}/${imdb-demo.db.name}
spring.datasource.username=${imdb-demo.db.user}
spring.datasource.password=${imdb-demo.db.pass}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
########################################################################################################################
# Servlet Configuration
spring.servlet.multipart.max-file-size=4GB
spring.servlet.multipart.max-request-size=4GB
########################################################################################################################
# Logging Configuration
logging.level.root=info
########################################################################################################################
# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true