spring.application.name=imdb-demo
spring.profiles.active=dev
########################################################################################################################
# Environment Variables
imdb-demo.host=${IMDB_DEMO_HOST:localhost}
imdb-demo.port=${IMDB_DEMO_PORT:8443}
imdb-demo.use-tls=${IMDB_DEMO_USE_TLS:false}
imdb-demo.db.host=${IMDB_DEMO_DB_HOST:localhost}
imdb-demo.db.port=${IMDB_DEMO_DB_PORT:5432}
imdb-demo.db.name=${IMDB_DEMO_DB_NAME:dev_imdb_demo}
imdb-demo.db.user=${IMDB_DEMO_DB_USER:postgres}
imdb-demo.db.pass=${IMDB_DEMO_DB_PASS:password}
imdb-demo.ks-path=${IMDB_DEMO_KS_PATH:classpath:certs/keystore.p12}
imdb-demo.ks-type=${IMDB_DEMO_KS_TYPE:PKCS12}
imdb-demo.ks-alias=${IMDB_DEMO_KS_ALIAS:imdb-demo-cert}
imdb-demo.ks-pass=${IMDB_DEMO_KS_PASS:changeit}
########################################################################################################################
# Server Configuration
server.address=${imdb-demo.host}
server.port=${imdb-demo.port}
########################################################################################################################
# TLS Configuration
server.ssl.enabled=${imdb-demo.use-tls}
server.ssl.key-store=${imdb-demo.ks-path}
server.ssl.key-store-type=${imdb-demo.ks-type}
server.ssl.key-store-password=${imdb-demo.ks-pass}
server.ssl.key-alias=${imdb-demo.ks-alias}
########################################################################################################################
# Datasource Configuration
spring.datasource.url=jdbc:postgresql://${imdb-demo.db.host}:${imdb-demo.db.port}/${imdb-demo.db.name}
spring.datasource.username=${imdb-demo.db.user}
spring.datasource.password=${imdb-demo.db.pass}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
########################################################################################################################
# Servlet Configuration
spring.servlet.multipart.max-file-size=4GB
spring.servlet.multipart.max-request-size=4GB
########################################################################################################################
# Logging Configuration
logging.level.root=info
########################################################################################################################
# JPA Configuration
spring.jpa.hibernate.ddl-auto=validate