spring.application.name=imdb-demo
########################################################################################################################
# Environment Variables
imdb-demo.host=${IMDB_DEMO_HOST:localhost}
imdb-demo.port=${IMDB_DEMO_PORT:8443}
imdb-demo.use-tls=${IMDB_DEMO_USE_TLS:false}
imdb-demo.temp-dir=${IMDB_DEMO_TEMP_DIR:/tmp/${spring.application.name}}
imdb-demo.db.host=${IMDB_DEMO_DB_HOST:localhost}
imdb-demo.db.port=${IMDB_DEMO_DB_PORT:5432}
imdb-demo.db.name=${IMDB_DEMO_DB_NAME:dev_imdb_demo}
imdb-demo.db.user=${IMDB_DEMO_DB_USER:postgres}
imdb-demo.db.pass=${IMDB_DEMO_DB_PASS:password}
imdb-demo.ks.path=${IMDB_DEMO_KS_PATH:classpath:tls/imdb-demo.p12}
imdb-demo.ks.type=${IMDB_DEMO_KS_TYPE:PKCS12}
imdb-demo.ks.alias=${IMDB_DEMO_KS_ALIAS:${spring.application.name}}
imdb-demo.ks.pass=${IMDB_DEMO_KS_PASS:changeit}
imdb-demo.ws.chunk.byte-size=${IMDB_DEMO_WS_CHUNK_BYTE_SIZE:1048576}
imdb-demo.ws.chunk.ack-interval=${IMDB_DEMO_WS_CHUNK_ACK_INTERVAL:20}
imdb-demo.ws.chunk.in-flight-max=${IMDB_DEMO_WS_CHUNK_IN_FLIGHT_MAX:150}
imdb-demo.ul.temp-dir=${IMDB_DEMO_UL_TEMP_DIR:${imdb-demo.temp-dir}/uploads}
imdb-demo.ul.queue-size=${IMDB_DEMO_UL_QUEUE_SIZE:2000}
########################################################################################################################
# WARNING: Altering anything below this line is unsupported - proceed at your own risk
########################################################################################################################
# Server
server.address=${imdb-demo.host}
server.port=${imdb-demo.port}
########################################################################################################################
# TLS
server.ssl.enabled=${imdb-demo.use-tls}
server.ssl.key-store=${imdb-demo.ks.path}
server.ssl.key-store-type=${imdb-demo.ks.type}
server.ssl.key-store-password=${imdb-demo.ks.pass}
server.ssl.key-alias=${imdb-demo.ks.alias}
########################################################################################################################
# Datasource
spring.datasource.url=jdbc:postgresql://${imdb-demo.db.host}:${imdb-demo.db.port}/${imdb-demo.db.name}
spring.datasource.username=${imdb-demo.db.user}
spring.datasource.password=${imdb-demo.db.pass}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
########################################################################################################################
# Servlet
spring.servlet.multipart.max-file-size=4GB
spring.servlet.multipart.max-request-size=4GB
########################################################################################################################
# JPA
spring.jpa.hibernate.ddl-auto=validate